name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'isimip_qa/**'
      - 'testing/**'
      - .pre-commit-config.yaml
      - conftest.py
      - pyproject.toml

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.8', '3.12']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install coveralls
        python -m pip install -e .[dev]

    - name: Run pytest
      run: |
        pytest --reuse-db --cov=isimip_data
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    needs: test
    runs-on: ubuntu-22.04
    container: python:3-slim

    steps:
    - name: Run coveralls finish
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
